// GROUP PERMISSIONS
export const GROUP_CREATE = 'GROUP_CREATE';
export const GROUP_UPDATE = 'GROUP_UPDATE';
export const GROUP_DELETE = 'GROUP_DELETE';
export const GROUP_LIST = 'GROUP_LIST';
export const GROUP_DETAILS = 'GROUP_DETAILS';

// POST_DATE_CHEQUE PERMISSION
export const POST_DATE_CHEQUE_CREATE = 'POST_DATE_CHEQUE_CREATE';
export const POST_DATE_CHEQUE_UPDATE = 'POST_DATE_CHEQUE_UPDATE';
export const POST_DATE_CHEQUE_DELETE = 'POST_DATE_CHEQUE_DELETE';
export const POST_DATE_CHEQUE_LIST = 'POST_DATE_CHEQUE_LIST';
export const POST_DATE_CHEQUE_DETAILS = 'POST_DATE_CHEQUE_DETAILS';
// LEDGER_ACCOUNT PERMISSIONS
export const LEDGER_ACCOUNT_CREATE = 'LEDGER_ACCOUNT_CREATE';
export const LEDGER_ACCOUNT_UPDATE = 'LEDGER_ACCOUNT_UPDATE';
export const LEDGER_ACCOUNT_DELETE = 'LEDGER_ACCOUNT_DELETE';
export const LEDGER_ACCOUNT_LIST = 'LEDGER_ACCOUNT_LIST';
export const LEDGER_ACCOUNT_DETAILS = 'LEDGER_ACCOUNT_DETAILS';

// SUBLEDGER PERMISSION
export const SUBLEDGER_ACCOUNT_CREATE = 'SUBLEDGER_ACCOUNT_CREATE';
export const SUBLEDGER_ACCOUNT_UPDATE = 'SUBLEDGER_ACCOUNT_UPDATE';
export const SUBLEDGER_ACCOUNT_DELETE = 'SUBLEDGER_ACCOUNT_DELETE';
export const SUBLEDGER_ACCOUNT_LIST = 'SUBLEDGER_ACCOUNT_LIST';
export const SUBLEDGER_ACCOUNT_DETAILS = 'SUBLEDGER_ACCOUNT_DETAILS';

// PAYMENT_VOUCHER PERMISSION
export const PAYMENT_VOUCHER_CREATE = 'PAYMENT_VOUCHER_CREATE';
export const PAYMENT_VOUCHER_UPDATE = 'PAYMENT_VOUCHER_UPDATE';
export const PAYMENT_VOUCHER_DELETE = 'PAYMENT_VOUCHER_DELETE';
export const PAYMENT_VOUCHER_LIST = 'PAYMENT_VOUCHER_LIST';
export const PAYMENT_VOUCHER_DETAILS = 'PAYMENT_VOUCHER_DETAILS';

// RECEIPT_VOUCHER PERMISSION
export const RECEIPT_VOUCHER_CREATE = 'RECEIPT_VOUCHER_CREATE';
export const RECEIPT_VOUCHER_UPDATE = 'RECEIPT_VOUCHER_UPDATE';
export const RECEIPT_VOUCHER_DELETE = 'RECEIPT_VOUCHER_DELETE';
export const RECEIPT_VOUCHER_LIST = 'RECEIPT_VOUCHER_LIST';
export const RECEIPT_VOUCHER_DETAILS = 'RECEIPT_VOUCHER_DETAILS';

// SALES PERMISSION
export const SALES_CREATE = 'SALES_CREATE';
export const SALES_UPDATE = 'SALES_UPDATE';
export const SALES_DELETE = 'SALES_DELETE';
export const SALES_LIST = 'SALES_LIST';
export const SALES_DETAILS = 'SALES_DETAILS';

// PURCHASE PERMISSION
export const PURCHASE_CREATE = 'PURCHASE_CREATE';
export const PURCHASE_UPDATE = 'PURCHASE_UPDATE';
export const PURCHASE_DELETE = 'PURCHASE_DELETE';
export const PURCHASE_LIST = 'PURCHASE_LIST';
export const PURCHASE_DETAILS = 'PURCHASE_DETAILS';

// CONTRA PERMISSION
export const CONTRA_CREATE = 'CONTRA_CREATE';
export const CONTRA_UPDATE = 'CONTRA_UPDATE';
export const CONTRA_DELETE = 'CONTRA_DELETE';
export const CONTRA_LIST = 'CONTRA_LIST';
export const CONTRA_DETAILS = 'CONTRA_DETAILS';

// JOURNAL PERMISSION
export const JOURNAL_CREATE = 'JOURNAL_CREATE';
export const JOURNAL_UPDATE = 'JOURNAL_UPDATE';
export const JOURNAL_DELETE = 'JOURNAL_DELETE';
export const JOURNAL_LIST = 'JOURNAL_LIST';
export const JOURNAL_DETAILS = 'JOURNAL_DETAILS';

// IDJOURNAL PERMISSION
export const IDJOURNAL_CREATE = 'IDJOURNAL_CREATE';
export const IDJOURNAL_UPDATE = 'IDJOURNAL_UPDATE';
export const IDJOURNAL_DELETE = 'IDJOURNAL_DELETE';
export const IDJOURNAL_LIST = 'IDJOURNAL_LIST';
export const IDJOURNAL_DETAILS = 'IDJOURNAL_DETAILS';

// ACCOUNT_LOG PERMISSION
export const ACCOUNT_LOG_CREATE = 'ACCOUNT_LOG_CREATE';
export const ACCOUNT_LOG_UPDATE = 'ACCOUNT_LOG_UPDATE';
export const ACCOUNT_LOG_DELETE = 'ACCOUNT_LOG_DELETE';
export const ACCOUNT_LOG_LIST = 'ACCOUNT_LOG_LIST';
export const ACCOUNT_LOG_DETAILS = 'ACCOUNT_LOG_DETAILS';

// ACCOUNT_UPDATE_PERMISSION PERMISSION
export const ACCOUNT_UPDATE_PERMISSION_CREATE = 'ACCOUNT_UPDATE_PERMISSION_CREATE';
export const ACCOUNT_UPDATE_PERMISSION_UPDATE = 'ACCOUNT_UPDATE_PERMISSION_UPDATE';
export const ACCOUNT_UPDATE_PERMISSION_DELETE = 'ACCOUNT_UPDATE_PERMISSION_DELETE';
export const ACCOUNT_UPDATE_PERMISSION_LIST = 'ACCOUNT_UPDATE_PERMISSION_LIST';
export const ACCOUNT_UPDATE_PERMISSION_DETAILS = 'ACCOUNT_UPDATE_PERMISSION_DETAILS';

// CURRENCY PERMISSIONS
export const CURRENCY_CREATE = 'CURRENCY_CREATE';
export const CURRENCY_UPDATE = 'CURRENCY_UPDATE';
export const CURRENCY_DELETE = 'CURRENCY_DELETE';
export const CURRENCY_LIST = 'CURRENCY_LIST';
export const CURRENCY_DETAILS = 'CURRENCY_DETAILS';

// AIRWAY PERMISSIONS
export const AIRWAY_CREATE = 'AIRWAY_CREATE';
export const AIRWAY_UPDATE = 'AIRWAY_UPDATE';
export const AIRWAY_DELETE = 'AIRWAY_DELETE';
export const AIRWAY_LIST = 'AIRWAY_LIST';
export const AIRWAY_DETAILS = 'AIRWAY_DETAILS';

// GDS PERMISSION
export const GDS_ACCOUNT_CREATE = 'GDS_ACCOUNT_CREATE';
export const GDS_ACCOUNT_UPDATE = 'GDS_ACCOUNT_UPDATE';
export const GDS_ACCOUNT_DELETE = 'GDS_ACCOUNT_DELETE';
export const GDS_ACCOUNT_LIST = 'GDS_ACCOUNT_LIST';
export const GDS_ACCOUNT_DETAILS = 'GDS_ACCOUNT_DETAILS';

// TICKET_PURCHASE PERMISSION
export const TICKET_PURCHASE_CREATE = 'TICKET_PURCHASE_CREATE';
export const TICKET_PURCHASE_UPDATE = 'TICKET_PURCHASE_UPDATE';
export const TICKET_PURCHASE_DELETE = 'TICKET_PURCHASE_DELETE';
export const TICKET_PURCHASE_DETAILS = 'TICKET_PURCHASE_DETAILS';

// IATATICKET_TEMPTEMP PERMISSION
export const IATATICKET_TEMPTEMP_CREATE = 'IATATICKET_TEMPTEMP_CREATE';
export const IATATICKET_TEMPTEMP_UPDATE = 'IATATICKET_TEMPTEMP_UPDATE';
export const IATATICKET_TEMPTEMP_DELETE = 'IATATICKET_TEMPTEMP_DELETE';
export const IATATICKET_TEMPTEMP_LIST = 'IATATICKET_TEMPTEMP_LIST';
export const IATATICKET_TEMPTEMP_DETAILS = 'IATATICKET_TEMPTEMP_DETAILS';

// IATATICKET_TEMPORARY PERMISSION
export const IATATICKET_TEMPORARY_CREATE = 'IATATICKET_TEMPORARY_CREATE';
export const IATATICKET_TEMPORARY_UPDATE = 'IATATICKET_TEMPORARY_UPDATE';
export const IATATICKET_TEMPORARY_DELETE = 'IATATICKET_TEMPORARY_DELETE';
export const IATATICKET_TEMPORARY_LIST = 'IATATICKET_TEMPORARY_LIST';
export const IATATICKET_TEMPORARY_DETAILS = 'IATATICKET_TEMPORARY_DETAILS';

// IATATICKET PERMISSION
export const IATATICKET_CREATE = 'IATATICKET_CREATE';
export const IATATICKET_UPDATE = 'IATATICKET_UPDATE';
export const IATATICKET_DELETE = 'IATATICKET_DELETE';
export const IATATICKET_LIST = 'IATATICKET_LIST';
export const IATATICKET_DETAILS = 'IATATICKET_DETAILS';

// TICKET_REFUND PERMISSION
export const TICKET_REFUND_CREATE = 'TICKET_REFUND_CREATE';
export const TICKET_REFUND_UPDATE = 'TICKET_REFUND_UPDATE';
export const TICKET_REFUND_DELETE = 'TICKET_REFUND_DELETE';
export const TICKET_REFUND_LIST = 'TICKET_REFUND_LIST';
export const TICKET_REFUND_DETAILS = 'TICKET_REFUND_DETAILS';

// TICKET_DEPUTE PERMISSION
export const TICKET_DEPUTE_CREATE = 'TICKET_DEPUTE_CREATE';
export const TICKET_DEPUTE_UPDATE = 'TICKET_DEPUTE_UPDATE';
export const TICKET_DEPUTE_DELETE = 'TICKET_DEPUTE_DELETE';
export const TICKET_DEPUTE_LIST = 'TICKET_DEPUTE_LIST';
export const TICKET_DEPUTE_DETAILS = 'TICKET_DEPUTE_DETAILS';

// AIRTICKET_UPDATE_PERMISSION PERMISSION
export const AIRTICKET_UPDATE_PERMISSION_CREATE = 'AIRTICKET_UPDATE_PERMISSION_CREATE';
export const AIRTICKET_UPDATE_PERMISSION_UPDATE = 'AIRTICKET_UPDATE_PERMISSION_UPDATE';
export const AIRTICKET_UPDATE_PERMISSION_DELETE = 'AIRTICKET_UPDATE_PERMISSION_DELETE';
export const AIRTICKET_UPDATE_PERMISSION_LIST = 'AIRTICKET_UPDATE_PERMISSION_LIST';
export const AIRTICKET_UPDATE_PERMISSION_DETAILS = 'AIRTICKET_UPDATE_PERMISSION_DETAILS';

// USER PERMISSIONS
export const USER_CREATE = 'USER_CREATE';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_DELETE = 'USER_DELETE';
export const USER_LIST = 'USER_LIST';
export const USER_DETAILS = 'USER_DETAILS';

// PERMISSION PERMISSIONS
export const PERMISSION_CREATE = 'PERMISSION_CREATE';
export const PERMISSION_UPDATE = 'PERMISSION_UPDATE';
export const PERMISSION_DELETE = 'PERMISSION_DELETE';
export const PERMISSION_LIST = 'PERMISSION_LIST';
export const PERMISSION_DETAILS = 'PERMISSION_DETAILS';

// ROLE PERMISSION
export const ROLE_CREATE = 'ROLE_CREATE';
export const ROLE_UPDATE = 'ROLE_UPDATE';
export const ROLE_DELETE = 'ROLE_DELETE';
export const ROLE_LIST = 'ROLE_LIST';
export const ROLE_DETAILS = 'ROLE_DETAILS';

// COUNTRY PERMISSION
export const COUNTRY_CREATE = 'COUNTRY_CREATE';
export const COUNTRY_UPDATE = 'COUNTRY_UPDATE';
export const COUNTRY_DELETE = 'COUNTRY_DELETE';
export const COUNTRY_LIST = 'COUNTRY_LIST';
export const COUNTRY_DETAILS = 'COUNTRY_DETAILS';

// CITY PERMISSION
export const CITY_CREATE = 'CITY_CREATE';
export const CITY_UPDATE = 'CITY_UPDATE';
export const CITY_DELETE = 'CITY_DELETE';
export const CITY_LIST = 'CITY_LIST';
export const CITY_DETAILS = 'CITY_DETAILS';

// THANA PERMISSION
export const THANA_CREATE = 'THANA_CREATE';
export const THANA_UPDATE = 'THANA_UPDATE';
export const THANA_DELETE = 'THANA_DELETE';
export const THANA_LIST = 'THANA_LIST';
export const THANA_DETAILS = 'THANA_DETAILS';

// AREA PERMISSION
export const AREA_CREATE = 'AREA_CREATE';
export const AREA_UPDATE = 'AREA_UPDATE';
export const AREA_DELETE = 'AREA_DELETE';
export const AREA_LIST = 'AREA_LIST';
export const AREA_DETAILS = 'AREA_DETAILS';

// BRANCH PERMISSION
export const BRANCH_CREATE = 'BRANCH_CREATE';
export const BRANCH_UPDATE = 'BRANCH_UPDATE';
export const BRANCH_DELETE = 'BRANCH_DELETE';
export const BRANCH_LIST = 'BRANCH_LIST';
export const BRANCH_DETAILS = 'BRANCH_DETAILS';

// DEPARTMENT PERMISSION
export const DEPARTMENT_CREATE = 'DEPARTMENT_CREATE';
export const DEPARTMENT_UPDATE = 'DEPARTMENT_UPDATE';
export const DEPARTMENT_DELETE = 'DEPARTMENT_DELETE';
export const DEPARTMENT_LIST = 'DEPARTMENT_LIST';
export const DEPARTMENT_DETAILS = 'DEPARTMENT_DETAILS';

// EMPLOYEE PERMISSION
export const EMPLOYEE_CREATE = 'EMPLOYEE_CREATE';
export const EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE';
export const EMPLOYEE_DELETE = 'EMPLOYEE_DELETE';
export const EMPLOYEE_LIST = 'EMPLOYEE_LIST';
export const EMPLOYEE_DETAILS = 'EMPLOYEE_DETAILS';

// QUALIFICATION PERMISSION
export const QUALIFICATION_CREATE = 'QUALIFICATION_CREATE';
export const QUALIFICATION_UPDATE = 'QUALIFICATION_UPDATE';
export const QUALIFICATION_DELETE = 'QUALIFICATION_DELETE';
export const QUALIFICATION_LIST = 'QUALIFICATION_LIST';
export const QUALIFICATION_DETAILS = 'QUALIFICATION_DETAILS';

// DESIGNATION PERMISSION
export const DESIGNATION_CREATE = 'DESIGNATION_CREATE';
export const DESIGNATION_UPDATE = 'DESIGNATION_UPDATE';
export const DESIGNATION_DELETE = 'DESIGNATION_DELETE';
export const DESIGNATION_LIST = 'DESIGNATION_LIST';
export const DESIGNATION_DETAILS = 'DESIGNATION_DETAILS';

// LOGIN_HISTORY PERMISSION
export const LOGIN_HISTORY_CREATE = 'LOGIN_HISTORY_CREATE';
export const LOGIN_HISTORY_UPDATE = 'LOGIN_HISTORY_UPDATE';
export const LOGIN_HISTORY_DELETE = 'LOGIN_HISTORY_DELETE';
export const LOGIN_HISTORY_LIST = 'LOGIN_HISTORY_LIST';
export const LOGIN_HISTORY_DETAILS = 'LOGIN_HISTORY_DETAILS';

// PROFESSION PERMISSIONS
export const PROFESSION_CREATE = 'PROFESSION_CREATE';
export const PROFESSION_UPDATE = 'PROFESSION_UPDATE';
export const PROFESSION_DELETE = 'PROFESSION_DELETE';
export const PROFESSION_LIST = 'PROFESSION_LIST';
export const PROFESSION_DETAILS = 'PROFESSION_DETAILS';

// AGENT AGENTS
export const AGENT_CREATE = 'AGENT_CREATE';
export const AGENT_UPDATE = 'AGENT_UPDATE';
export const AGENT_DELETE = 'AGENT_DELETE';
export const AGENT_LIST = 'AGENT_LIST';
export const AGENT_DETAILS = 'AGENT_DETAILS';

// CVBANK PERMISSION
export const CVBANK_CREATE = 'CVBANK_CREATE';
export const CVBANK_UPDATE = 'CVBANK_UPDATE';
export const CVBANK_DELETE = 'CVBANK_DELETE';
export const CVBANK_LIST = 'CVBANK_LIST';
export const CVBANK_DETAILS = 'CVBANK_DETAILS';

// DEMAND PERMISSION
export const DEMAND_CREATE = 'DEMAND_CREATE';
export const DEMAND_UPDATE = 'DEMAND_UPDATE';
export const DEMAND_DELETE = 'DEMAND_DELETE';
export const DEMAND_LIST = 'DEMAND_LIST';
export const DEMAND_DETAILS = 'DEMAND_DETAILS';

// VISA_ENTRY PERMISSION
export const VISA_ENTRY_CREATE = 'VISA_ENTRY_CREATE';
export const VISA_ENTRY_UPDATE = 'VISA_ENTRY_UPDATE';
export const VISA_ENTRY_DELETE = 'VISA_ENTRY_DELETE';
export const VISA_ENTRY_LIST = 'VISA_ENTRY_LIST';
export const VISA_ENTRY_DETAILS = 'VISA_ENTRY_DETAILS';

// PASSENGER_TYPE PERMISSION
export const PASSENGER_TYPE_CREATE = 'PASSENGER_TYPE_CREATE';
export const PASSENGER_TYPE_UPDATE = 'PASSENGER_TYPE_UPDATE';
export const PASSENGER_TYPE_DELETE = 'PASSENGER_TYPE_DELETE';
export const PASSENGER_TYPE_LIST = 'PASSENGER_TYPE_LIST';
export const PASSENGER_TYPE_DETAILS = 'PASSENGER_TYPE_DETAILS';

// CURRENT_STATUS PERMISSION
export const CURRENT_STATUS_CREATE = 'CURRENT_STATUS_CREATE';
export const CURRENT_STATUS_UPDATE = 'CURRENT_STATUS_UPDATE';
export const CURRENT_STATUS_DELETE = 'CURRENT_STATUS_DELETE';
export const CURRENT_STATUS_LIST = 'CURRENT_STATUS_LIST';
export const CURRENT_STATUS_DETAILS = 'CURRENT_STATUS_DETAILS';

// RECRUITING_AGENCY PERMISSION
export const RECRUITING_AGENCY_CREATE = 'RECRUITING_AGENCY_CREATE';
export const RECRUITING_AGENCY_UPDATE = 'RECRUITING_AGENCY_UPDATE';
export const RECRUITING_AGENCY_DELETE = 'RECRUITING_AGENCY_DELETE';
export const RECRUITING_AGENCY_LIST = 'RECRUITING_AGENCY_LIST';
export const RECRUITING_AGENCY_DETAILS = 'RECRUITING_AGENCY_DETAILS';

// PASSENGER PERMISSION
export const PASSENGER_CREATE = 'PASSENGER_CREATE';
export const PASSENGER_UPDATE = 'PASSENGER_UPDATE';
export const PASSENGER_DELETE = 'PASSENGER_DELETE';
export const PASSENGER_LIST = 'PASSENGER_LIST';
export const PASSENGER_DETAILS = 'PASSENGER_DETAILS';

// PASSPORT_SUBMISSION PERMISSION
export const PASSPORT_SUBMISSION_CREATE = 'PASSPORT_SUBMISSION_CREATE';
export const PASSPORT_SUBMISSION_UPDATE = 'PASSPORT_SUBMISSION_UPDATE';
export const PASSPORT_SUBMISSION_DELETE = 'PASSPORT_SUBMISSION_DELETE';
export const PASSPORT_SUBMISSION_LIST = 'PASSPORT_SUBMISSION_LIST';
export const PASSPORT_SUBMISSION_DETAILS = 'PASSPORT_SUBMISSION_DETAILS';

// DEPARTURE PERMISSION
export const DEPARTURE_CREATE = 'DEPARTURE_CREATE';
export const DEPARTURE_UPDATE = 'DEPARTURE_UPDATE';
export const DEPARTURE_DELETE = 'DEPARTURE_DELETE';
export const DEPARTURE_LIST = 'DEPARTURE_LIST';
export const DEPARTURE_DETAILS = 'DEPARTURE_DETAILS';

// MEDICAL_CENTER PERMISSIONS
export const MEDICAL_CENTER_CREATE = 'MEDICAL_CENTER_CREATE';
export const MEDICAL_CENTER_UPDATE = 'MEDICAL_CENTER_UPDATE';
export const MEDICAL_CENTER_DELETE = 'MEDICAL_CENTER_DELETE';
export const MEDICAL_CENTER_LIST = 'MEDICAL_CENTER_LIST';
export const MEDICAL_CENTER_DETAILS = 'MEDICAL_CENTER_DETAILS';

// MEDICAL MEDICALS
export const MEDICAL_CREATE = 'MEDICAL_CREATE';
export const MEDICAL_UPDATE = 'MEDICAL_UPDATE';
export const MEDICAL_DELETE = 'MEDICAL_DELETE';
export const MEDICAL_LIST = 'MEDICAL_LIST';
export const MEDICAL_DETAILS = 'MEDICAL_DETAILS';

// MOFA PERMISSION
export const MOFA_CREATE = 'MOFA_CREATE';
export const MOFA_UPDATE = 'MOFA_UPDATE';
export const MOFA_DELETE = 'MOFA_DELETE';
export const MOFA_LIST = 'MOFA_LIST';
export const MOFA_DETAILS = 'MOFA_DETAILS';

// OFFICE_WORK PERMISSION
export const OFFICE_WORK_CREATE = 'OFFICE_WORK_CREATE';
export const OFFICE_WORK_UPDATE = 'OFFICE_WORK_UPDATE';
export const OFFICE_WORK_DELETE = 'OFFICE_WORK_DELETE';
export const OFFICE_WORK_LIST = 'OFFICE_WORK_LIST';
export const OFFICE_WORK_DETAILS = 'OFFICE_WORK_DETAILS';

// MUSANED_OKALA PERMISSION
export const MUSANED_OKALA_CREATE = 'MUSANED_OKALA_CREATE';
export const MUSANED_OKALA_UPDATE = 'MUSANED_OKALA_UPDATE';
export const MUSANED_OKALA_DELETE = 'MUSANED_OKALA_DELETE';
export const MUSANED_OKALA_LIST = 'MUSANED_OKALA_LIST';
export const MUSANED_OKALA_DETAILS = 'MUSANED_OKALA_DETAILS';

// EMBASSY PERMISSION
export const EMBASSY_CREATE = 'EMBASSY_CREATE';
export const EMBASSY_UPDATE = 'EMBASSY_UPDATE';
export const EMBASSY_DELETE = 'EMBASSY_DELETE';
export const EMBASSY_LIST = 'EMBASSY_LIST';
export const EMBASSY_DETAILS = 'EMBASSY_DETAILS';

// TRAINING PERMISSION
export const TRAINING_CREATE = 'TRAINING_CREATE';
export const TRAINING_UPDATE = 'TRAINING_UPDATE';
export const TRAINING_DELETE = 'TRAINING_DELETE';
export const TRAINING_LIST = 'TRAINING_LIST';
export const TRAINING_DETAILS = 'TRAINING_DETAILS';

// MANPOWER PERMISSION
export const MANPOWER_CREATE = 'MANPOWER_CREATE';
export const MANPOWER_UPDATE = 'MANPOWER_UPDATE';
export const MANPOWER_DELETE = 'MANPOWER_DELETE';
export const MANPOWER_LIST = 'MANPOWER_LIST';
export const MANPOWER_DETAILS = 'MANPOWER_DETAILS';

// FLIGHT PERMISSION
export const FLIGHT_CREATE = 'FLIGHT_CREATE';
export const FLIGHT_UPDATE = 'FLIGHT_UPDATE';
export const FLIGHT_DELETE = 'FLIGHT_DELETE';
export const FLIGHT_LIST = 'FLIGHT_LIST';
export const FLIGHT_DETAILS = 'FLIGHT_DETAILS';

// FEMALE_CV PERMISSION
export const FEMALE_CV_CREATE = 'FEMALE_CV_CREATE';
export const FEMALE_CV_UPDATE = 'FEMALE_CV_UPDATE';
export const FEMALE_CV_DELETE = 'FEMALE_CV_DELETE';
export const FEMALE_CV_LIST = 'FEMALE_CV_LIST';
export const FEMALE_CV_DETAILS = 'FEMALE_CV_DETAILS';

// MALE_CV PERMISSION
export const MALE_CV_CREATE = 'MALE_CV_CREATE';
export const MALE_CV_UPDATE = 'MALE_CV_UPDATE';
export const MALE_CV_DELETE = 'MALE_CV_DELETE';
export const MALE_CV_LIST = 'MALE_CV_LIST';
export const MALE_CV_DETAILS = 'MALE_CV_DETAILS';

// COMPLAIN PERMISSION
export const COMPLAIN_CREATE = 'COMPLAIN_CREATE';
export const COMPLAIN_UPDATE = 'COMPLAIN_UPDATE';
export const COMPLAIN_DELETE = 'COMPLAIN_DELETE';
export const COMPLAIN_LIST = 'COMPLAIN_LIST';
export const COMPLAIN_DETAILS = 'COMPLAIN_DETAILS';

// VISA_SUBMISSION_LIST PERMISSION
export const VISA_SUBMISSION_LIST_CREATE = 'VISA_SUBMISSION_LIST_CREATE';
export const VISA_SUBMISSION_LIST_UPDATE = 'VISA_SUBMISSION_LIST_UPDATE';
export const VISA_SUBMISSION_LIST_DELETE = 'VISA_SUBMISSION_LIST_DELETE';
export const VISA_SUBMISSION_LIST_LIST = 'VISA_SUBMISSION_LIST_LIST';
export const VISA_SUBMISSION_LIST_DETAILS = 'VISA_SUBMISSION_LIST_DETAILS';

// VISA_CANCEL_LIST PERMISSION
export const VISA_CANCEL_LIST_CREATE = 'VISA_CANCEL_LIST_CREATE';
export const VISA_CANCEL_LIST_UPDATE = 'VISA_CANCEL_LIST_UPDATE';
export const VISA_CANCEL_LIST_DELETE = 'VISA_CANCEL_LIST_DELETE';
export const VISA_CANCEL_LIST_LIST = 'VISA_CANCEL_LIST_LIST';
export const VISA_CANCEL_LIST_DETAILS = 'VISA_CANCEL_LIST_DETAILS';

// VISA_REISSUE_LIST PERMISSION
export const VISA_REISSUE_LIST_CREATE = 'VISA_REISSUE_LIST_CREATE';
export const VISA_REISSUE_LIST_UPDATE = 'VISA_REISSUE_LIST_UPDATE';
export const VISA_REISSUE_LIST_DELETE = 'VISA_REISSUE_LIST_DELETE';
export const VISA_REISSUE_LIST_LIST = 'VISA_REISSUE_LIST_LIST';
export const VISA_REISSUE_LIST_DETAILS = 'VISA_REISSUE_LIST_DETAILS';

// MANPOWER_LIST PERMISSION
export const MANPOWER_LIST_CREATE = 'MANPOWER_LIST_CREATE';
export const MANPOWER_LIST_UPDATE = 'MANPOWER_LIST_UPDATE';
export const MANPOWER_LIST_DELETE = 'MANPOWER_LIST_DELETE';
export const MANPOWER_LIST_LIST = 'MANPOWER_LIST_LIST';
export const MANPOWER_LIST_DETAILS = 'MANPOWER_LIST_DETAILS';

// CALLING_EMB_ATTESTATION PERMISSION
export const CALLING_EMB_ATTESTATION_CREATE = 'CALLING_EMB_ATTESTATION_CREATE';
export const CALLING_EMB_ATTESTATION_UPDATE = 'CALLING_EMB_ATTESTATION_UPDATE';
export const CALLING_EMB_ATTESTATION_DELETE = 'CALLING_EMB_ATTESTATION_DELETE';
export const CALLING_EMB_ATTESTATION_LIST = 'CALLING_EMB_ATTESTATION_LIST';
export const CALLING_EMB_ATTESTATION_DETAILS = 'CALLING_EMB_ATTESTATION_DETAILS';

// MAKE_LIST PERMISSION
export const MAKE_LIST_CREATE = 'MAKE_LIST_CREATE';
export const MAKE_LIST_UPDATE = 'MAKE_LIST_UPDATE';
export const MAKE_LIST_DELETE = 'MAKE_LIST_DELETE';
export const MAKE_LIST_LIST = 'MAKE_LIST_LIST';
export const MAKE_LIST_DETAILS = 'MAKE_LIST_DETAILS';

// MAKE_LIST_ITEM PERMISSION
export const MAKE_LIST_ITEM_CREATE = 'MAKE_LIST_ITEM_CREATE';
export const MAKE_LIST_ITEM_UPDATE = 'MAKE_LIST_ITEM_UPDATE';
export const MAKE_LIST_ITEM_DELETE = 'MAKE_LIST_ITEM_DELETE';
export const MAKE_LIST_ITEM_LIST = 'MAKE_LIST_ITEM_LIST';
export const MAKE_LIST_ITEM_DETAILS = 'MAKE_LIST_ITEM_DETAILS';

// MAKE_LIST_COLUMN PERMISSION
export const MAKE_LIST_COLUMN_CREATE = 'MAKE_LIST_COLUMN_CREATE';
export const MAKE_LIST_COLUMN_UPDATE = 'MAKE_LIST_COLUMN_UPDATE';
export const MAKE_LIST_COLUMN_DELETE = 'MAKE_LIST_COLUMN_DELETE';
export const MAKE_LIST_COLUMN_LIST = 'MAKE_LIST_COLUMN_LIST';
export const MAKE_LIST_COLUMN_DETAILS = 'MAKE_LIST_COLUMN_DETAILS';

// MENU_ITEM PERMISSIONS
export const MENU_ITEM_CREATE = 'MENU_ITEM_CREATE';
export const MENU_ITEM_UPDATE = 'MENU_ITEM_UPDATE';
export const MENU_ITEM_DELETE = 'MENU_ITEM_DELETE';
export const MENU_ITEM_LIST = 'MENU_ITEM_LIST';
export const MENU_ITEM_DETAILS = 'MENU_ITEM_DETAILS';

// ROLE_MENU PERMISSIONS
export const ROLE_MENU_CREATE = 'ROLE_MENU_CREATE';
export const ROLE_MENU_UPDATE = 'ROLE_MENU_UPDATE';
export const ROLE_MENU_DELETE = 'ROLE_MENU_DELETE';
export const ROLE_MENU_LIST = 'ROLE_MENU_LIST';
export const ROLE_MENU_DETAILS = 'ROLE_MENU_DETAILS';

// GENERAL_SETTING PERMISSION
export const GENERAL_SETTING_CREATE = 'GENERAL_SETTING_CREATE';
export const GENERAL_SETTING_UPDATE = 'GENERAL_SETTING_UPDATE';
export const GENERAL_SETTING_DELETE = 'GENERAL_SETTING_DELETE';
export const GENERAL_SETTING_LIST = 'GENERAL_SETTING_LIST';
export const GENERAL_SETTING_DETAILS = 'GENERAL_SETTING_DETAILS';

// HOMEPAGE_SLIDER PERMISSION
export const HOMEPAGE_SLIDER_CREATE = 'HOMEPAGE_SLIDER_CREATE';
export const HOMEPAGE_SLIDER_UPDATE = 'HOMEPAGE_SLIDER_UPDATE';
export const HOMEPAGE_SLIDER_DELETE = 'HOMEPAGE_SLIDER_DELETE';
export const HOMEPAGE_SLIDER_LIST = 'HOMEPAGE_SLIDER_LIST';
export const HOMEPAGE_SLIDER_DETAILS = 'HOMEPAGE_SLIDER_DETAILS';

// TICKET_DEPARTMENT PERMISSIONS
export const TICKET_DEPARTMENT_CREATE = 'TICKET_DEPARTMENT_CREATE';
export const TICKET_DEPARTMENT_UPDATE = 'TICKET_DEPARTMENT_UPDATE';
export const TICKET_DEPARTMENT_DELETE = 'TICKET_DEPARTMENT_DELETE';
export const TICKET_DEPARTMENT_LIST = 'TICKET_DEPARTMENT_LIST';
export const TICKET_DEPARTMENT_DETAILS = 'TICKET_DEPARTMENT_DETAILS';

// TICKET_PRIORITY PERMISSION
export const TICKET_PRIORITY_CREATE = 'TICKET_PRIORITY_CREATE';
export const TICKET_PRIORITY_UPDATE = 'TICKET_PRIORITY_UPDATE';
export const TICKET_PRIORITY_DELETE = 'TICKET_PRIORITY_DELETE';
export const TICKET_PRIORITY_LIST = 'TICKET_PRIORITY_LIST';
export const TICKET_PRIORITY_DETAILS = 'TICKET_PRIORITY_DETAILS';

// TICKET_STATUS PERMISSION
export const TICKET_STATUS_CREATE = 'TICKET_STATUS_CREATE';
export const TICKET_STATUS_UPDATE = 'TICKET_STATUS_UPDATE';
export const TICKET_STATUS_DELETE = 'TICKET_STATUS_DELETE';
export const TICKET_STATUS_LIST = 'TICKET_STATUS_LIST';
export const TICKET_STATUS_DETAILS = 'TICKET_STATUS_DETAILS';

// TICKET PERMISSION
export const TICKET_CREATE = 'TICKET_CREATE';
export const TICKET_UPDATE = 'TICKET_UPDATE';
export const TICKET_DELETE = 'TICKET_DELETE';
export const TICKET_LIST = 'TICKET_LIST';
export const TICKET_DETAILS = 'TICKET_DETAILS';

// TICKET_DETAIL PERMISSION
export const TICKET_DETAIL_CREATE = 'TICKET_DETAIL_CREATE';
export const TICKET_DETAIL_UPDATE = 'TICKET_DETAIL_UPDATE';
export const TICKET_DETAIL_DELETE = 'TICKET_DETAIL_DELETE';
export const TICKET_DETAIL_LIST = 'TICKET_DETAIL_LIST';
export const TICKET_DETAIL_DETAILS = 'TICKET_DETAIL_DETAILS';

// MESSAGE PERMISSION
export const MESSAGE_CREATE = 'MESSAGE_CREATE';
export const MESSAGE_UPDATE = 'MESSAGE_UPDATE';
export const MESSAGE_DELETE = 'MESSAGE_DELETE';
export const MESSAGE_LIST = 'MESSAGE_LIST';
export const MESSAGE_DETAILS = 'MESSAGE_DETAILS';

// TASK_TYPE PERMISSION
export const TASK_TYPE_CREATE = 'TASK_TYPE_CREATE';
export const TASK_TYPE_UPDATE = 'TASK_TYPE_UPDATE';
export const TASK_TYPE_DELETE = 'TASK_TYPE_DELETE';
export const TASK_TYPE_LIST = 'TASK_TYPE_LIST';
export const TASK_TYPE_DETAILS = 'TASK_TYPE_DETAILS';

// TODO_TASK PERMISSION
export const TODO_TASK_CREATE = 'TODO_TASK_CREATE';
export const TODO_TASK_UPDATE = 'TODO_TASK_UPDATE';
export const TODO_TASK_DELETE = 'TODO_TASK_DELETE';
export const TODO_TASK_LIST = 'TODO_TASK_LIST';
export const TODO_TASK_DETAILS = 'TODO_TASK_DETAILS';

// MAIL_DOCUMENT
export const MAIL_DOCUMENT = 'MAIL_DOCUMENT';

// VISA_ENTRY PERMISSION
export const MULTIPLE_VISA_ENTRY_CREATE = 'MULTIPLE_VISA_ENTRY_CREATE';

// RECEIPT_VOIUCHER_REPORT PERMISSION
export const RECEIPT_VOIUCHER_REPORT_LIST = 'RECEIPT_VOIUCHER_REPORT_LIST';

// PAYMENT_VOIUCHER_REPORT PERMISSION
export const PAYMENT_VOIUCHER_REPORT_LIST = 'PAYMENT_VOIUCHER_REPORT_LIST';

// SALES_REPORT PERMISSION
export const SALES_REPORT_LIST = 'SALES_REPORT_LIST';

// PURCHASE_REPORT PERMISSION
export const PURCHASE_REPORT_LIST = 'PURCHASE_REPORT_LIST';

// CONTRA_REPORT PERMISSION
export const CONTRA_REPORT_LIST = 'CONTRA_REPORT_LIST';

export const PAYMENT_VOIUCHER_SUMMARY_LIST = 'PAYMENT_VOIUCHER_SUMMARY_LIST';

export const RECEIPT_VOIUCHER_SUMMARY_LIST = 'RECEIPT_VOIUCHER_SUMMARY_LIST';
// ACCOUNT_LOG_REPORT PERMISSION (LEDGER REPORT)
export const ACCOUNT_LOG_REPORT_LIST = 'ACCOUNT_LOG_REPORT_LIST';
export const ACCOUNT_LOG_REPORT_BY_LEDGER_TYPE_LIST = 'ACCOUNT_LOG_REPORT_LIST';
export const ACCOUNT_LOG_REPORT_CASH_BANK = 'ACCOUNT_LOG_REPORT_CASH_BANK';

// BALANCE SHEET
export const BALANCE_SHEET_LIST = 'BALANCE_SHEET_LIST';
export const PROFIT_LOSS_LIST = 'PROFIT_LOSS_LIST';
export const TRIAL_BALANCE_LIST = 'TRIAL_BALANCE_LIST';

// REPORT
export const AGENT_REPORT = 'AGENT_REPORT';
export const PASSENGER_REPORT = 'PASSENGER_REPORT';
export const MEDICAL_REPORT = 'MEDICAL_REPORT';
export const EMBASSY_REPORT = 'EMBASSY_REPORT';
export const MOFA_REPORT = 'MOFA_REPORT';
export const TRAINING_REPORT = 'TRAINING_REPORT';
export const MANPOWER_REPORT = 'MANPOWER_REPORT';
export const FLIGHT_REPORT = 'FLIGHT_REPORT';
export const PASSENGER_SUMMARY_REPORT = 'PASSENGER_SUMMARY_REPORT';

export const TICKET_PURCHASE_LIST = 'IATA_TICKET_TEMPORARY_LIST';
export const IATA_TICKET_TEMPORARY_LIST = 'IATA_TICKET_TEMPORARY_LIST';
export const IATA_TICKET_LIST = 'IATA_TICKET_LIST';
// export const TICKET_REFUND_LIST='TICKET_REFUND_LIST'
// export const TICKET_DEPUTE_LIST='TICKET_DEPUTE_LIST'
export const IATA_TICKET_SUMMARY = 'IATA_TICKET_SUMMARY';
export const BMET_FORM = 'BMET_FORM';
export const KSA_VISA_FORM = 'KSA_VISA_FORM';
//  export const PASSENGER_DETAILS='PASSENGER_DETAILS'
export const FINGER_FORM = 'FINGER_FORM';
export const DEPARTURE_CARD = 'DEPARTURE_CARD';

// ACTIVITY_LOG PERMISSION
export const ACTIVITY_LOG_CREATE = 'ACTIVITY_LOG_CREATE';
export const ACTIVITY_LOG_UPDATE = 'ACTIVITY_LOG_UPDATE';
export const ACTIVITY_LOG_DELETE = 'ACTIVITY_LOG_DELETE';
export const ACTIVITY_LOG_LIST = 'ACTIVITY_LOG_LIST';
export const ACTIVITY_LOG_DETAILS = 'ACTIVITY_LOG_DETAILS';

export const IATATICKET_TEMPORARY_TO_IATATICKET = 'IATATICKET_TEMPORARY_TO_IATATICKET';

export const IATATicketTempTempToIATATicketTemporary = 'IATATicketTempTempToIATATicketTemporary';

export const MEDICAL_COUNTS = 'MEDICAL_COUNTS';
export const EMBASSY_COUNTS = 'EMBASSY_COUNTS';
export const MANPOWER_COUNTS = 'MANPOWER_COUNTS';
export const FLIGHT_COUNTS = 'FLIGHT_COUNTS';

export const VISA_SUBMISSION_LIST_DATA = 'VISA_SUBMISSION_LIST_DATA';
export const MANPOWER_LIST_DATA = 'MANPOWER_LIST_DATA';
export const MANPOWER_LIST_NOTESHEET_DATA = 'MANPOWER_LIST_NOTESHEET_DATA';
