import _ from '@lodash';

const CvBankModel = (data) =>
	_.defaults(data || {}, {
		passenger_name: '',
		date_of_birth: '',
		gender: '',
		tracking_no: '',
		travel_year: '',
		serial_no: '',
		office_serial: '',
		nid: '',
		father_name: '',
		mother_name: '',
		spouse_name: '',
		religion: '',
		marital_status: '',
		passport_no: '',
		passport_type: '',
		passport_issue_date: '',
		passport_expiry_date: '',
		village: '',
		post_office: '',
		contact_no: '',
		emergency_contact_no: '',
		passport_issue_place: '',
		passport_pic: '',
		passenger_pic: '',
		notes: '',
		post: '',
		qualification: '',
		experience: '',
		year_of_experience: '',
		place_of_birth: '',
		place_of_residence: '',
		number_of_children: '',
		height: '',
		weight: '',
		language_skill: '',
		education: '',
		arabic_skill: '',
		english_skill: '',
		salary: '',
		complexion: '',
		remarks: '',
		file: '',
		agent: '',
		agency: '',
		target_country: '',
		passenger_type: '',
		current_status: '',
		police_station: '',
		district: '',
		profession: ''
	});
export default CvBankModel;
