import _ from '@lodash';

const TicketSaleModel = (data) =>
  _.defaults(data || {}, {
    airline_commission_amount: 0,
    airline_commission_rate: 7,
    airline_pnr: 0,
    arrived_time: '',
    branch: '',
    check_tax: '',
    currency: '',
    current_airway: '',
    customer: '',
    customer_commission_amount: 0,
    customer_commission_rate: 7,
    detail: '',
    dollar_amount: 0,
    dollar_rate: 0,
    fare_amount: 0,
    final_passenger: '',
    flight_date: '',
    flight_no: '',
    flight_time: '',
    gds: '',
    gds_pnr: '',
    govt_vat_rate: 7,
    invoice_no: '',
    issue_date: '',
    issue_person: '',
    passenger: '',
    passport_copy: '',
    passport_no: '',
    pax_name: '',
    purchase_amount: 0,
    return_flight_date: '',
    sales_amount: 0,
    sector: '',
    service_charge: 0,
    tax_amount: 0,
    ticket_agency: '',
    ticket_copy: '',
    ticket_no: '',
    ticket_status: 'active',
    _class: '',
  });
export default TicketSaleModel;
