import { apiService as api } from 'app/store/apiService';
import { GET_SAUDI_DASHBOARD_LATEST_SAUDIS } from 'src/app/constant/constants';

// Define the tag types for cache management
export const addTagTypes = ['saudi', 'SaudiDashboardProjects'];

const SaudiDashboardApi = api
  .enhanceEndpoints({
    addTagTypes,
  })
  .injectEndpoints({
    endpoints: (build) => ({
      // Fetch upcoming medical data
      getSaudiDashboardTotalSaudi: build.query({
        query: (filterData) => ({
          url: GET_SAUDI_DASHBOARD_LATEST_SAUDIS,
          params: filterData,
        }),

        providesTags: ['saudi'],
      }),

      // Fetch project saudi projects
      getSaudiDashboardProjects: build.query({
        query: () => ({
          url: '/mock-api/saudis/project/projects',
        }),
        providesTags: ['SaudiDashboardProjects'],
      }),
    }),
    overrideExisting: false,
  });

// Export the hooks generated by RTK Query
export const { useGetSaudiDashboardTotalSaudiQuery } = SaudiDashboardApi;

// Selector to fetch a specific widget by ID
export const selectWidget = (id) => (state) => {
  const widgets =
    SaudiDashboardApi.endpoints.getSaudiDashboardTotalSaudi.select()(
      state
    )?.data;
  return widgets?.[id];
};

export default SaudiDashboardApi;
